# The image that carries the SMARTCyp tools.
#
# This used to be generated by the bmuschko 'docker-java-application' Gradle
# plugin from a single 'baseImage' line, which meant you could not build or
# inspect the image without running Gradle, and the layout was whatever that
# plugin version happened to emit. It is now an ordinary two-stage build:
# 'installDist' collects the application jar and its dependencies, and the
# runtime stage carries nothing but a JRE and those jars.

FROM eclipse-temurin:21.0.12_8-jdk-noble AS build

WORKDIR /build

# The build definition on its own first, so that editing a source file does not
# re-download Gradle and the whole dependency graph.
COPY gradlew settings.gradle ./
COPY gradle ./gradle
COPY app/build.gradle ./app/
RUN ./gradlew --no-daemon --console=plain :app:dependencies --configuration runtimeClasspath > /dev/null

COPY app/src ./app/src
RUN ./gradlew --no-daemon --console=plain :app:installDist

FROM eclipse-temurin:21.0.12_8-jre-noble AS final

LABEL maintainer="Tim Dudgeon <tdudgeon@informaticsmatters.com>"

# 'installDist' puts the application jar and every runtime dependency here.
COPY --from=build /build/app/build/install/app/lib /app/libs

# The Job Definition runs 'java squonk.jobs.smartcyp.Predictor ...' with no
# '-cp', so the classpath has to reach the JVM through the environment. The
# predecessor image also listed '/app/resources' and '/app/classes', which the
# plugin created for the unpacked application classes; 'installDist' jars those
# instead, so only 'libs' is left.
ENV CLASSPATH="/app/libs/*"

# There is deliberately no ENTRYPOINT of our own: the Job Definition supplies
# the whole command. Note that the eclipse-temurin base does set one
# ('/__cacert_entrypoint.sh'), which execs its arguments - Kubernetes replaces
# it outright when the Data Manager sets 'command'.
CMD ["java", "-version"]
