/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package squonk.jobs.smartcyp

import org.openscience.cdk.interfaces.IAtomContainer
import org.openscience.cdk.smiles.SmilesParser
import org.openscience.cdk.DefaultChemObjectBuilder
import spock.lang.Specification

class PredictorTest extends Specification {

    def "application has a greeting"() {
        setup:
        def predictor = new Predictor(true, true, true, true, null, null, null)
        SmilesParser sp  = new SmilesParser(DefaultChemObjectBuilder.getInstance());
        IAtomContainer mol   = sp.parseSmiles("c1ccccc1");

        when:
        def result = predictor.calculateMol(mol)

        then:
        result != null
    }
}
