---
# Tools using the Chemistry Development Kit
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: CDK jobs
collection: smartcyp

jobs:
  smartcyp-prediction:
    name: P450 predictions using SmartCyp
    description: >-
      Cytochrome P450 predictions using SmartCyp
    version: '1.0.0'
    category: comp chem
    keywords:
    - cdk
    - smartcyp
    - prediction
    - p450
    image:
      name: informaticsmatters/squonk2-smartcyp
      tag: 'latest'
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    # The container has no entrypoint so this is the command that is executed.
    # The CLASSPATH environment variable in the container is set.
    command: >-
      java squonk.jobs.smartcyp.Predictor
      --input '{{ inputFile }}'
      --output '{{ outputFile }}'
      {% if calcGeneral is defined and calcGeneral %}--calc-general{% endif %}
      {% if calc2D6 is defined and calc2D6 %}--calc-2d6{% endif %}
      {% if calc2C9 is defined and calc2C9 %}--calc-2c9{% endif %}
      {% if empirical is defined and empirical %}--empirical{% endif %}
      {% if maxRank is defined and maxRank %}--max-rank {{ maxRank }}{% endif %}
      {% if threshold is defined and threshold %}--threshold {{ threshold }}{% endif %}
      --interval 5000
    variables:
      order:
        options:
        - outputFile
        - calcGeneral
        - calc2D6
        - calc2C9
        - empirical
        - maxRank
        - threshold
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: Input molecules
            mime-types:
            - chemical/x-mdl-sdfile
            type: file
      outputs:
        type: object
        properties:
          results:
            title: Output molecules
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}'
            type: file
            annotation-properties:
              fields-descriptor:
                origin: squonk2-job
                description: P450 predictions using SmartCyp
                fields:
                  SMARTCyp_GEN:
                    type: text
                    description: >-
                      General P450 prediction
                    required: false
                    active: true
                  SMARTCyp_2D6:
                    type: text
                    description: >-
                      Cyp 2D6 prediction
                    required: false
                    active: true
                  SMARTCyp_2C9:
                    type: text
                    description: >-
                      Cyp 2C9 prediction
                    required: false
                    active: true
              service-execution:
                service_ref: 'https://discourse.squonk.it/t/job-cdk-molecular-descriptors/126'
              derived-from: inputFile
      options:
        type: object
        required:
        - outputFile
        properties:
          outputFile:
            title: Output file (.sdf)
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
          calcGeneral:
            title: Calculate general reactivity
            type: boolean
            default: true
          calc2D6:
            title: Calculate 2D6 reactivity
            type: boolean
            default: true
          calc2C9:
            title: Calculate 2C9 reactivity
            type: boolean
            default: true
          empirical:
            title: Apply empirical N-Oxidation corrections
            type: boolean
            default: true
          maxRank:
            title: Maximum rank
            type: integer
            default: 3
          threshold:
            title: Score threshold
            type: number
    tests:
      simple-sdf:
        inputs:
          inputFile: data/dhfr_3d-10.sdf
        options:
          outputFile: foo/cyp-predictions.sdf
          calcGeneral: true
          calc2D6: true
          calc2Cp: true
          empirical: true
          maxRank: 3
        checks:
          exitCode: 0
          outputs:
          - name: foo/cyp-predictions.sdf
            checks:
            - exists: true
      simple-smiles:
        inputs:
          inputFile: data/100.smi
        options:
          outputFile: foo/cyp-predictions.sdf
          calcGeneral: true
          calc2D6: true
          calc2Cp: true
          empirical: true
          maxRank: 3
        checks:
          exitCode: 0
          outputs:
          - name: foo/cyp-predictions.sdf
            checks:
            - exists: true
